M48
; DRILL file {KiCad (6.0.0-0)} date Monday, January 03, 2022 at 08:25:50 pm
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-03T20:25:50-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.66Y-2.66
X2.66Y-5.31
X9.61Y-2.66
X9.61Y-5.31
T0
M30
